### ISSUE TITLE
Ctrl+C causes panic

### ISSUE THREAD

**Issue by yonas** [caio-ishikawa/slingshot#6]
`Panic occurred: PanicInfo { payload: Any { .. }, message: Some(not implemented), location: Location { file: "src/event_handler.rs", line: 66, col: 18 }, can_unwind: true }`

**Comment by caio-ishikawa** [comment]
Yeah, I should have made it so that Ctrl+C exits the application like Esc does. Feel free to create a PR for it, otherwise I'll try to do it later today with some better documentation for keybinds

**Comment by yonas** [comment]
https://github.com/caio-ishikawa/slingshot/pull/7

**Comment by caio-ishikawa** [comment]
Resolved 👍
